export const iconList = [
    { "nome": "fa-arrow-down", "palavras_chave": ["seta para baixo", "descer", "direção"] },
    { "nome": "fa-arrow-left", "palavras_chave": ["seta para esquerda", "voltar", "direção"] },
    { "nome": "fa-arrow-right", "palavras_chave": ["seta para direita", "avançar", "direção"] },
    { "nome": "fa-arrow-up", "palavras_chave": ["seta para cima", "subir", "direção"] },
    { "nome": "fa-bars", "palavras_chave": ["menu", "hambúrguer", "navegação"] },
    { "nome": "fa-bicycle", "palavras_chave": ["bicicleta", "transporte", "ciclismo"] },
    { "nome": "fa-bus", "palavras_chave": ["ônibus", "transporte público"] },
    { "nome": "fa-car", "palavras_chave": ["carro", "veículo", "transporte"] },
    { "nome": "fa-check", "palavras_chave": ["verificado", "certo", "concluído"] },
    { "nome": "fa-chevron-down", "palavras_chave": ["chevron para baixo", "descer", "direção"] },
    { "nome": "fa-chevron-left", "palavras_chave": ["chevron para esquerda", "voltar", "direção"] },
    { "nome": "fa-chevron-right", "palavras_chave": ["chevron para direita", "avançar", "direção"] },
    { "nome": "fa-chevron-up", "palavras_chave": ["chevron para cima", "subir", "direção"] },
    { "nome": "fa-cog", "palavras_chave": ["engrenagem", "configurações", "ajustes"] },
    { "nome": "fa-credit-card", "palavras_chave": ["cartão de crédito", "pagamento", "finanças"] },
    { "nome": "fa-database", "palavras_chave": ["banco de dados", "armazenamento", "tecnologia"] },
    { "nome": "fa-desktop", "palavras_chave": ["desktop", "computador", "tecnologia"] },
    { "nome": "fa-dollar-sign", "palavras_chave": ["dólar", "dinheiro", "moeda", "finanças"] },
    { "nome": "fa-envelope", "palavras_chave": ["envelope", "email", "mensagem", "correio"] },
    { "nome": "fa-exclamation-triangle", "palavras_chave": ["alerta", "aviso", "erro"] },
    { "nome": "fa-file", "palavras_chave": ["arquivo", "documento", "folha"] },
    { "nome": "fa-file-alt", "palavras_chave": ["arquivo alternativo", "documento", "texto"] },
    { "nome": "fa-folder", "palavras_chave": ["pasta", "diretório", "organização"] },
    { "nome": "fa-folder-open", "palavras_chave": ["pasta aberta", "diretório", "organização"] },
    { "nome": "fa-graduation-cap", "palavras_chave": ["formatura", "educação", "universidade"] },
    { "nome": "fa-heart", "palavras_chave": ["coração", "favorito", "like", "amor"] },
    { "nome": "fa-heart-pulse", "palavras_chave": ["saúde", "batimento cardíaco", "bem-estar"] },
    { "nome": "fa-heartbeat", "palavras_chave": ["batimento cardíaco", "saúde", "medicina"] },
    { "nome": "fa-home", "palavras_chave": ["casa", "início", "lar", "home"] },
    { "nome": "fa-hospital", "palavras_chave": ["hospital", "saúde", "medicina"] },
    { "nome": "fa-id-badge", "palavras_chave": ["identificação", "crachá", "acesso"] },
    { "nome": "fa-info-circle", "palavras_chave": ["informação", "detalhes", "ajuda"] },
    { "nome": "fa-leaf", "palavras_chave": ["folha", "natureza", "sustentabilidade"] },
    { "nome": "fa-lightbulb", "palavras_chave": ["ideia", "criatividade", "inovação"] },
    { "nome": "fa-laptop", "palavras_chave": ["laptop", "computador", "tecnologia"] },
    { "nome": "fa-masks-theater", "palavras_chave": ["teatro", "máscaras", "cultura"] },
    { "nome": "fa-medkit", "palavras_chave": ["kit médico", "saúde", "emergência"] },
    { "nome": "fa-minus", "palavras_chave": ["remover", "diminuir", "negativo"] },
    { "nome": "fa-mobile", "palavras_chave": ["celular", "smartphone", "tecnologia"] },
    { "nome": "fa-music", "palavras_chave": ["música", "nota", "som"] },
    { "nome": "fa-pause", "palavras_chave": ["pausar", "parar", "mídia"] },
    { "nome": "fa-people-roof", "palavras_chave": ["comunidade", "família", "abrigo"] },
    { "nome": "fa-phone", "palavras_chave": ["telefone", "chamada", "contato"] },
    { "nome": "fa-plane", "palavras_chave": ["avião", "viagem", "transporte"] },
    { "nome": "fa-play", "palavras_chave": ["play", "iniciar", "reproduzir"] },
    { "nome": "fa-plus", "palavras_chave": ["adicionar", "aumentar", "positivo"] },
    { "nome": "fa-print", "palavras_chave": ["imprimir", "impressora", "documento"] },
    { "nome": "fa-road", "palavras_chave": ["estrada", "caminho", "infraestrutura"] },
    { "nome": "fa-save", "palavras_chave": ["salvar", "guardar", "disco"] },
    { "nome": "fa-search", "palavras_chave": ["busca", "pesquisa", "lupa"] },
    { "nome": "fa-shield-halved", "palavras_chave": ["segurança", "proteção", "escudo"] },
    { "nome": "fa-shopping-cart", "palavras_chave": ["carrinho de compras", "e-commerce", "loja"] },
    { "nome": "fa-star", "palavras_chave": ["estrela", "favorito", "classificação"] },
    { "nome": "fa-stethoscope", "palavras_chave": ["estetoscópio", "médico", "saúde"] },
    { "nome": "fa-stop", "palavras_chave": ["parar", "interromper", "mídia"] },
    { "nome": "fa-tablet", "palavras_chave": ["tablet", "dispositivo", "tecnologia"] },
    { "nome": "fa-tag", "palavras_chave": ["etiqueta", "preço", "promoção"] },
    { "nome": "fa-tags", "palavras_chave": ["etiquetas", "categorias", "organização"] },
    { "nome": "fa-thumbs-down", "palavras_chave": ["polegar para baixo", "desaprovar"] },
    { "nome": "fa-thumbs-up", "palavras_chave": ["polegar para cima", "curtir", "aprovar"] },
    { "nome": "fa-times", "palavras_chave": ["fechar", "cancelar", "x"] },
    { "nome": "fa-train", "palavras_chave": ["trem", "transporte", "trilhos"] },
    { "nome": "fa-user", "palavras_chave": ["usuário", "perfil", "pessoa", "conta"] },
    { "nome": "fa-users", "palavras_chave": ["usuários", "pessoas", "grupo"] },
    { "nome": "fa-volume-down", "palavras_chave": ["volume baixo", "som", "áudio"] },
    { "nome": "fa-volume-off", "palavras_chave": ["mudo", "silenciar", "áudio"] },
    { "nome": "fa-volume-up", "palavras_chave": ["volume alto", "som", "áudio"] },
]
